const armorCounts = {"current": {"0": 0, "1": 0, "2": 0, "3": 0, "4": 0, "upgradeless": 0}, "total": {"0": 104, "1": 104, "2": 104, "3": 104, "4": 104, "upgradeless": 32}};

const armorList = [
	{ id: 0, name: "Archaic Tunic", maxlevel: 0, bodypart: "Torso", effect: false, set: false, def: [1], upgrade: [] },
	{ id: 1, name: "Archaic Legwear", maxlevel: 0, bodypart: "Legs", effect: false, set: false, def: [1], upgrade: [] },
	{ id: 2, name: "Archaic Warm Greaves", maxlevel: 0, bodypart: "Legs", effect: "Cold Resistance", set: false, def: [2], upgrade: [] },
	{ id: 3, name: "Hylian Hood", maxlevel: 4, bodypart: "Head", effect: false, set: "Hylian", def: [3, 5, 8, 12, 20], upgrade: [null,{"Bokoblin Horn":5,"Rupees":10},{"Blue Bokoblin Horn":5,"Bokoblin Fang":3,"Rupees":50},{"Black Bokoblin Horn":5,"Bokoblin Guts":3,"Amber":20,"Rupees":200},{"Silver Bokoblin Horn":5,"Bokoblin Guts":5,"Amber":30,"Rupees":500}] },
	{ id: 4, name: "Hylian Hood (Down)", maxlevel: 4, bodypart: "Head", effect: false, set: "Hylian", def: [3, 5, 8, 12, 20], upgrade: [null,{"Bokoblin Horn":5,"Rupees":10},{"Blue Bokoblin Horn":5,"Bokoblin Fang":3,"Rupees":50},{"Black Bokoblin Horn":5,"Bokoblin Guts":3,"Amber":20,"Rupees":200},{"Silver Bokoblin Horn":5,"Bokoblin Guts":5,"Amber":30,"Rupees":500}] },
	{ id: 5, name: "Hylian Tunic", maxlevel: 4, bodypart: "Torso", effect: false, set: "Hylian", def: [3, 5, 8, 12, 20], upgrade: [null,{"Bokoblin Horn":5,"Rupees":10},{"Blue Bokoblin Horn":5,"Bokoblin Fang":3,"Rupees":50},{"Black Bokoblin Horn":5,"Bokoblin Guts":3,"Amber":20,"Rupees":200},{"Silver Bokoblin Horn":5,"Bokoblin Guts":5,"Amber":30,"Rupees":500}] },
	{ id: 6, name: "Hylian Trousers", maxlevel: 4, bodypart: "Legs", effect: false, set: "Hylian", def: [3, 5, 8, 12, 20], upgrade: [null,{"Bokoblin Horn":5,"Rupees":10},{"Blue Bokoblin Horn":5,"Bokoblin Fang":3,"Rupees":50},{"Black Bokoblin Horn":5,"Bokoblin Guts":3,"Amber":20,"Rupees":200},{"Silver Bokoblin Horn":5,"Bokoblin Guts":5,"Amber":30,"Rupees":500}] },
	{ id: 7, name: "Soldier's Helm", maxlevel: 4, bodypart: "Head", effect: false, set: "Soldier's", def: [4, 7, 12, 18, 28], upgrade: [null,{"Chuchu Jelly":5,"Bokoblin Guts":3,"Rupees":10},{"Keese Eyeball":5,"Moblin Guts":3,"Rupees":50},{"Lizalfos Tail":3,"Hinox Guts":3,"Flint":30,"Rupees":200},{"Lynel Hoof":5,"Lynel Guts":5,"Amber":30,"Rupees":500}] },
	{ id: 8, name: "Soldier's Armor", maxlevel: 4, bodypart: "Torso", effect: false, set: "Soldier's", def: [4, 7, 12, 18, 28], upgrade: [null,{"Chuchu Jelly":5,"Bokoblin Guts":3,"Rupees":10},{"Keese Eyeball":5,"Moblin Guts":3,"Rupees":50},{"Lizalfos Tail":3,"Hinox Guts":3,"Flint":30,"Rupees":200},{"Lynel Hoof":5,"Lynel Guts":5,"Amber":30,"Rupees":500}] },
	{ id: 9, name: "Soldier's Greaves", maxlevel: 4, bodypart: "Legs", effect: false, set: "Soldier's", def: [4, 7, 12, 18, 28], upgrade: [null,{"Chuchu Jelly":5,"Bokoblin Guts":3,"Rupees":10},{"Keese Eyeball":5,"Moblin Guts":3,"Rupees":50},{"Lizalfos Tail":3,"Hinox Guts":3,"Flint":30,"Rupees":200},{"Lynel Hoof":5,"Lynel Guts":5,"Amber":30,"Rupees":500}] },
	{ id: 10, name: "Snowquill Headdress", maxlevel: 4, bodypart: "Head", effect: "Cold Resistance", set: "Snowquill", def: [3, 5, 8, 12, 20], upgrade: [null,{"Red Chuchu Jelly":3,"Rupees":10},{"Red Chuchu Jelly":5,"Warm Safflina":3,"Rupees":50},{"Fire Keese Wing":5,"Fire-Breath Lizalfos Tail":3,"Sunshroom":5,"Rupees":200},{"Fire-Breath Lizalfos Horn":5,"Fire-Breath Lizalfos Tail":10,"Ruby":5,"Rupees":500}] },
	{ id: 11, name: "Snowquill Tunic", maxlevel: 4, bodypart: "Torso", effect: "Cold Resistance", set: "Snowquill", def: [3, 5, 8, 12, 20], upgrade: [null,{"Red Chuchu Jelly":3,"Rupees":10},{"Red Chuchu Jelly":5,"Warm Safflina":3,"Rupees":50},{"Fire Keese Wing":5,"Fire-Breath Lizalfos Tail":3,"Sunshroom":5,"Rupees":200},{"Fire-Breath Lizalfos Horn":5,"Fire-Breath Lizalfos Tail":10,"Ruby":5,"Rupees":500}] },
	{ id: 12, name: "Snowquill Trousers", maxlevel: 4, bodypart: "Legs", effect: "Cold Resistance", set: "Snowquill", def: [3, 5, 8, 12, 20], upgrade: [null,{"Red Chuchu Jelly":3,"Rupees":10},{"Red Chuchu Jelly":5,"Warm Safflina":3,"Rupees":50},{"Fire Keese Wing":5,"Fire-Breath Lizalfos Tail":3,"Sunshroom":5,"Rupees":200},{"Fire-Breath Lizalfos Horn":5,"Fire-Breath Lizalfos Tail":10,"Ruby":5,"Rupees":500}] },
	{ id: 13, name: "Flamebreaker Helm", maxlevel: 4, bodypart: "Head", effect: "Flame Guard", set: "Flamebreaker", def: [3, 5, 8, 12, 20], upgrade: [null,{"Moblin Horn":3,"Rupees":10},{"Moblin Fang":5,"Fireproof Lizard":5,"Rupees":50},{"Blue Moblin Horn":5,"Smotherwing Butterfly":3,"Flint":15,"Rupees":200},{"Black Moblin Horn":5,"Smotherwing Butterfly":5,"Flint":30,"Rupees":500}] },
	{ id: 14, name: "Flamebreaker Armor", maxlevel: 4, bodypart: "Torso", effect: "Flame Guard", set: "Flamebreaker", def: [3, 5, 8, 12, 20], upgrade: [null,{"Moblin Horn":3,"Rupees":10},{"Moblin Fang":5,"Fireproof Lizard":5,"Rupees":50},{"Blue Moblin Horn":5,"Smotherwing Butterfly":3,"Flint":15,"Rupees":200},{"Black Moblin Horn":5,"Smotherwing Butterfly":5,"Flint":30,"Rupees":500}] },
	{ id: 15, name: "Flamebreaker Boots", maxlevel: 4, bodypart: "Legs", effect: "Flame Guard", set: "Flamebreaker", def: [3, 5, 8, 12, 20], upgrade: [null,{"Moblin Horn":3,"Rupees":10},{"Moblin Fang":5,"Fireproof Lizard":5,"Rupees":50},{"Blue Moblin Horn":5,"Smotherwing Butterfly":3,"Flint":15,"Rupees":200},{"Black Moblin Horn":5,"Smotherwing Butterfly":5,"Flint":30,"Rupees":500}] },
	{ id: 16, name: "Zora Helm", maxlevel: 4, bodypart: "Head", effect: "Swim Speed Up", set: "Zora", def: [3, 5, 8, 12, 20], upgrade: [null,{"Lizalfos Horn":3,"Rupees":10},{"Lizalfos Talon":5,"Hyrule Bass":5,"Rupees":50},{"Blue Lizalfos Horn":5,"Lizalfos Tail":3,"Hearty Bass":3,"Rupees":200},{"Black Lizalfos Horn":5,"Blue Lizalfos Tail":5,"Opal":20,"Rupees":500}] },
	{ id: 17, name: "Zora Armor", maxlevel: 4, bodypart: "Torso", effect: "Swim Speed Up", set: "Zora", def: [3, 5, 8, 12, 20], upgrade: [null,{"Lizalfos Horn":3,"Rupees":10},{"Lizalfos Talon":5,"Hyrule Bass":5,"Rupees":50},{"Blue Lizalfos Horn":5,"Lizalfos Tail":3,"Hearty Bass":3,"Rupees":200},{"Black Lizalfos Horn":5,"Blue Lizalfos Tail":5,"Opal":20,"Rupees":500}] },
	{ id: 18, name: "Zora Greaves", maxlevel: 4, bodypart: "Legs", effect: "Swim Speed Up", set: "Zora", def: [3, 5, 8, 12, 20], upgrade: [null,{"Lizalfos Horn":3,"Rupees":10},{"Lizalfos Talon":5,"Hyrule Bass":5,"Rupees":50},{"Blue Lizalfos Horn":5,"Lizalfos Tail":3,"Hearty Bass":3,"Rupees":200},{"Black Lizalfos Horn":5,"Blue Lizalfos Tail":5,"Opal":20,"Rupees":500}] },
	{ id: 19, name: "Desert Voe Headband", maxlevel: 4, bodypart: "Head", effect: "Heat Resistance", set: "Desert Voe", def: [3, 5, 8, 12, 20], upgrade: [null,{"White Chuchu Jelly":3,"Rupees":10},{"White Chuchu Jelly":5,"Cool Safflina":3,"Rupees":50},{"Ice Keese Wing":5,"Ice-Breath Lizalfos Tail":3,"Chillshroom":5,"Rupees":200},{"Ice-Breath Lizalfos Horn":5,"Ice-Breath Lizalfos Tail":10,"Sapphire":5,"Rupees":500}] },
	{ id: 20, name: "Desert Voe Spaulder", maxlevel: 4, bodypart: "Torso", effect: "Heat Resistance", set: "Desert Voe", def: [3, 5, 8, 12, 20], upgrade: [null,{"White Chuchu Jelly":3,"Rupees":10},{"White Chuchu Jelly":5,"Cool Safflina":3,"Rupees":50},{"Ice Keese Wing":5,"Ice-Breath Lizalfos Tail":3,"Chillshroom":5,"Rupees":200},{"Ice-Breath Lizalfos Horn":5,"Ice-Breath Lizalfos Tail":10,"Sapphire":5,"Rupees":500}] },
	{ id: 21, name: "Desert Voe Trousers", maxlevel: 4, bodypart: "Legs", effect: "Heat Resistance", set: "Desert Voe", def: [3, 5, 8, 12, 20], upgrade: [null,{"White Chuchu Jelly":3,"Rupees":10},{"White Chuchu Jelly":5,"Cool Safflina":3,"Rupees":50},{"Ice Keese Wing":5,"Ice-Breath Lizalfos Tail":3,"Chillshroom":5,"Rupees":200},{"Ice-Breath Lizalfos Horn":5,"Ice-Breath Lizalfos Tail":10,"Sapphire":5,"Rupees":500}] },
	{ id: 22, name: "Rubber Helm", maxlevel: 4, bodypart: "Head", effect: "Shock Resistance", set: "Rubber", def: [3, 5, 8, 12, 20], upgrade: [null,{"Electric Lizalfos Horn":1,"Yellow Chuchu Jelly":3,"Rupees":10},{"Yellow Chuchu Jelly":8,"Voltfruit":5,"Rupees":50},{"Zapshroom":5,"Electric Lizalfos Tail":5,"Electric Safflina":8,"Rupees":200},{"Electric Lizalfos Horn":5,"Topaz":5,"Electric Lizalfos Tail":8,"Rupees":500}] },
	{ id: 23, name: "Rubber Armor", maxlevel: 4, bodypart: "Torso", effect: "Shock Resistance", set: "Rubber", def: [3, 5, 8, 12, 20], upgrade: [null,{"Electric Lizalfos Horn":1,"Yellow Chuchu Jelly":3,"Rupees":10},{"Yellow Chuchu Jelly":8,"Voltfruit":5,"Rupees":50},{"Zapshroom":5,"Electric Lizalfos Tail":5,"Electric Safflina":8,"Rupees":200},{"Electric Lizalfos Horn":5,"Topaz":5,"Electric Lizalfos Tail":8,"Rupees":500}] },
	{ id: 24, name: "Rubber Tights", maxlevel: 4, bodypart: "Legs", effect: "Shock Resistance", set: "Rubber", def: [3, 5, 8, 12, 20], upgrade: [null,{"Electric Lizalfos Horn":1,"Yellow Chuchu Jelly":3,"Rupees":10},{"Yellow Chuchu Jelly":8,"Voltfruit":5,"Rupees":50},{"Zapshroom":5,"Electric Lizalfos Tail":5,"Electric Safflina":8,"Rupees":200},{"Electric Lizalfos Horn":5,"Topaz":5,"Electric Lizalfos Tail":8,"Rupees":500}] },
	{ id: 25, name: "Stealth Mask", maxlevel: 4, bodypart: "Head", effect: "Stealth Up", set: "Stealth", def: [2, 4, 6, 9, 16], upgrade: [null,{"Blue Nightshade":3,"Rupees":10},{"Blue Nightshade":5,"Sunset Firefly":5,"Rupees":50},{"Silent Shroom":8,"Sneaky River Snail":5,"Sticky Frog":5,"Rupees":200},{"Stealthfin Trout":10,"Silent Princess":5,"Sundelion":10,"Rupees":500}] },
	{ id: 26, name: "Stealth Chest Guard", maxlevel: 4, bodypart: "Torso", effect: "Stealth Up", set: "Stealth", def: [2, 4, 6, 9, 16], upgrade: [null,{"Blue Nightshade":3,"Rupees":10},{"Blue Nightshade":5,"Sunset Firefly":5,"Rupees":50},{"Silent Shroom":8,"Sneaky River Snail":5,"Sticky Frog":5,"Rupees":200},{"Stealthfin Trout":10,"Silent Princess":5,"Sundelion":10,"Rupees":500}] },
	{ id: 27, name: "Stealth Tights", maxlevel: 4, bodypart: "Legs", effect: "Stealth Up", set: "Stealth", def: [2, 4, 6, 9, 16], upgrade: [null,{"Blue Nightshade":3,"Rupees":10},{"Blue Nightshade":5,"Sunset Firefly":5,"Rupees":50},{"Silent Shroom":8,"Sneaky River Snail":5,"Sticky Frog":5,"Rupees":200},{"Stealthfin Trout":10,"Silent Princess":5,"Sundelion":10,"Rupees":500}] },
	{ id: 28, name: "Climber's Bandanna", maxlevel: 4, bodypart: "Head", effect: "Climb Speed Up", set: "Climbing Gear", def: [3, 5, 8, 12, 20], upgrade: [null,{"Keese Wing":3,"Rushroom":3,"Rupees":10},{"Electric Keese Wing":5,"Hightail Lizard":5,"Rupees":50},{"Ice Keese Wing":8,"Hot-Footed Frog":10,"Rupees":200},{"Fire Keese Wing":10,"Swift Violet":20,"Rupees":500}] },
	{ id: 29, name: "Climbing Gear", maxlevel: 4, bodypart: "Torso", effect: "Climb Speed Up", set: "Climbing Gear", def: [3, 5, 8, 12, 20], upgrade: [null,{"Keese Wing":3,"Rushroom":3,"Rupees":10},{"Electric Keese Wing":5,"Hightail Lizard":5,"Rupees":50},{"Ice Keese Wing":8,"Hot-Footed Frog":10,"Rupees":200},{"Fire Keese Wing":10,"Swift Violet":20,"Rupees":500}] },
	{ id: 30, name: "Climbing Boots", maxlevel: 4, bodypart: "Legs", effect: "Climb Speed Up", set: "Climbing Gear", def: [3, 5, 8, 12, 20], upgrade: [null,{"Keese Wing":3,"Rushroom":3,"Rupees":10},{"Electric Keese Wing":5,"Hightail Lizard":5,"Rupees":50},{"Ice Keese Wing":8,"Hot-Footed Frog":10,"Rupees":200},{"Fire Keese Wing":10,"Swift Violet":20,"Rupees":500}] },
	{ id: 31, name: "Barbarian Helm", maxlevel: 4, bodypart: "Head", effect: "Attack Up", set: "Barbarian", def: [3, 5, 8, 12, 20], upgrade: [null,{"Mighty Thistle":3,"Rupees":10},{"Lynel Saber Horn":2,"Lynel Mace Horn":2,"Razorshroom":5,"Rupees":50},{"Blue-Maned Lynel Saber Horn":3,"Blue-Maned Lynel Mace Horn":3,"Razorclaw Crab":3,"Rupees":200},{"White-Maned Lynel Saber Horn":3,"White-Maned Lynel Mace Horn":3,"Bladed Rhino Beetle":3,"Rupees":500}] },
	{ id: 32, name: "Barbarian Armor", maxlevel: 4, bodypart: "Torso", effect: "Attack Up", set: "Barbarian", def: [3, 5, 8, 12, 20], upgrade: [null,{"Mighty Thistle":3,"Rupees":10},{"Lynel Saber Horn":2,"Lynel Mace Horn":2,"Razorshroom":5,"Rupees":50},{"Blue-Maned Lynel Saber Horn":3,"Blue-Maned Lynel Mace Horn":3,"Razorclaw Crab":3,"Rupees":200},{"White-Maned Lynel Saber Horn":3,"White-Maned Lynel Mace Horn":3,"Bladed Rhino Beetle":3,"Rupees":500}] },
	{ id: 33, name: "Barbarian Leg Wraps", maxlevel: 4, bodypart: "Legs", effect: "Attack Up", set: "Barbarian", def: [3, 5, 8, 12, 20], upgrade: [null,{"Mighty Thistle":3,"Rupees":10},{"Lynel Saber Horn":2,"Lynel Mace Horn":2,"Razorshroom":5,"Rupees":50},{"Blue-Maned Lynel Saber Horn":3,"Blue-Maned Lynel Mace Horn":3,"Razorclaw Crab":3,"Rupees":200},{"White-Maned Lynel Saber Horn":3,"White-Maned Lynel Mace Horn":3,"Bladed Rhino Beetle":3,"Rupees":500}] },
	{ id: 34, name: "Radiant Mask", maxlevel: 4, bodypart: "Head", effect: false, set: "Radiant", def: [3, 5, 8, 12, 20], upgrade: [null,{"Luminous Stone":10,"Bokoblin Guts":1,"Rupees":10},{"Luminous Stone":15,"Moblin Guts":2,"Rupees":50},{"Luminous Stone":20,"Horriblin Guts":3,"Gibdo Bone":10,"Rupees":200},{"Luminous Stone":30,"Lynel Guts":3,"Molduga Jaw":3,"Rupees":500}] },
	{ id: 35, name: "Radiant Shirt", maxlevel: 4, bodypart: "Torso", effect: false, set: "Radiant", def: [3, 5, 8, 12, 20], upgrade: [null,{"Luminous Stone":10,"Bokoblin Guts":1,"Rupees":10},{"Luminous Stone":15,"Moblin Guts":2,"Rupees":50},{"Luminous Stone":20,"Horriblin Guts":3,"Gibdo Bone":10,"Rupees":200},{"Luminous Stone":30,"Lynel Guts":3,"Molduga Jaw":3,"Rupees":500}] },
	{ id: 36, name: "Radiant Tights", maxlevel: 4, bodypart: "Legs", effect: false, set: "Radiant", def: [3, 5, 8, 12, 20], upgrade: [null,{"Luminous Stone":10,"Bokoblin Guts":1,"Rupees":10},{"Luminous Stone":15,"Moblin Guts":2,"Rupees":50},{"Luminous Stone":20,"Horriblin Guts":3,"Gibdo Bone":10,"Rupees":200},{"Luminous Stone":30,"Lynel Guts":3,"Molduga Jaw":3,"Rupees":500}] },
	{ id: 37, name: "Royal Guard Cap", maxlevel: 4, bodypart: "Head", effect: false, set: "Royal Guard", def: [4, 6, 10, 15, 24], upgrade: [null,{"Boss Bokoblin Horn":3,"Bokoblin Guts":3,"Rupees":10},{"Blue Boss Bokoblin Horn":3,"Boss Bokoblin Guts":3,"Rupees":50},{"Black Boss Bokoblin Horn":3,"Hinox Guts":3,"Rupees":200},{"Silver Boss Bokoblin Horn":3,"Molduga Guts":3,"Gleeok Guts":3,"Rupees":500}] },
	{ id: 38, name: "Royal Guard Uniform", maxlevel: 4, bodypart: "Torso", effect: false, set: "Royal Guard", def: [4, 6, 10, 15, 24], upgrade: [null,{"Boss Bokoblin Horn":3,"Bokoblin Guts":3,"Rupees":10},{"Blue Boss Bokoblin Horn":3,"Boss Bokoblin Guts":3,"Rupees":50},{"Black Boss Bokoblin Horn":3,"Hinox Guts":3,"Rupees":200},{"Silver Boss Bokoblin Horn":3,"Molduga Guts":3,"Gleeok Guts":3,"Rupees":500}] },
	{ id: 39, name: "Royal Guard Boots", maxlevel: 4, bodypart: "Legs", effect: false, set: "Royal Guard", def: [4, 6, 10, 15, 24], upgrade: [null,{"Boss Bokoblin Horn":3,"Bokoblin Guts":3,"Rupees":10},{"Blue Boss Bokoblin Horn":3,"Boss Bokoblin Guts":3,"Rupees":50},{"Black Boss Bokoblin Horn":3,"Hinox Guts":3,"Rupees":200},{"Silver Boss Bokoblin Horn":3,"Molduga Guts":3,"Gleeok Guts":3,"Rupees":500}] },
	{ id: 40, name: "Froggy Hood", maxlevel: 4, bodypart: "Head", effect: "Slip Resistance", set: "Froggy", def: [3, 5, 8, 12, 20], upgrade: [null,{"Sticky Lizard":3,"Rupees":10},{"Horriblin Horn":5,"Sticky Lizard":5,"Rupees":50},{"Blue Horriblin Horn":5,"Sticky Frog":5,"Rupees":200},{"Black Horriblin Horn":5,"Horriblin Guts":10,"Opal":10,"Rupees":500}] },
	{ id: 41, name: "Froggy Sleeve", maxlevel: 4, bodypart: "Torso", effect: "Slip Resistance", set: "Froggy", def: [3, 5, 8, 12, 20], upgrade: [null,{"Sticky Lizard":3,"Rupees":10},{"Horriblin Horn":5,"Sticky Lizard":5,"Rupees":50},{"Blue Horriblin Horn":5,"Sticky Frog":5,"Rupees":200},{"Black Horriblin Horn":5,"Horriblin Guts":10,"Opal":10,"Rupees":500}] },
	{ id: 42, name: "Froggy Leggings", maxlevel: 4, bodypart: "Legs", effect: "Slip Resistance", set: "Froggy", def: [3, 5, 8, 12, 20], upgrade: [null,{"Sticky Lizard":3,"Rupees":10},{"Horriblin Horn":5,"Sticky Lizard":5,"Rupees":50},{"Blue Horriblin Horn":5,"Sticky Frog":5,"Rupees":200},{"Black Horriblin Horn":5,"Horriblin Guts":10,"Opal":10,"Rupees":500}] },
	{ id: 43, name: "Glide Mask", maxlevel: 4, bodypart: "Head", effect: "Skydive Mobility Up", set: "Glide", def: [2, 4, 6, 9, 16], upgrade: [null,{"Keese Wing":3,"Rupees":10},{"Aerocuda Eyeball":6,"Keese Wing":5,"Rupees":50},{"Aerocuda Wing":6,"Aerocuda Eyeball":8,"Rupees":200},{"Gleeok Wing":12,"Aerocuda Wing":10,"Gibdo Wing":8,"Rupees":500}] },
	{ id: 44, name: "Glide Shirt", maxlevel: 4, bodypart: "Torso", effect: "Skydive Mobility Up", set: "Glide", def: [2, 4, 6, 9, 16], upgrade: [null,{"Keese Wing":3,"Rupees":10},{"Aerocuda Eyeball":6,"Keese Wing":5,"Rupees":50},{"Aerocuda Wing":6,"Aerocuda Eyeball":8,"Rupees":200},{"Gleeok Wing":12,"Aerocuda Wing":10,"Gibdo Wing":8,"Rupees":500}] },
	{ id: 45, name: "Glide Tights", maxlevel: 4, bodypart: "Legs", effect: "Skydive Mobility Up", set: "Glide", def: [2, 4, 6, 9, 16], upgrade: [null,{"Keese Wing":3,"Rupees":10},{"Aerocuda Eyeball":6,"Keese Wing":5,"Rupees":50},{"Aerocuda Wing":6,"Aerocuda Eyeball":8,"Rupees":200},{"Gleeok Wing":12,"Aerocuda Wing":10,"Gibdo Wing":8,"Rupees":500}] },
	{ id: 46, name: "Hood of the Depths", maxlevel: 4, bodypart: "Head", effect: "Gloom Resistance", set: "Depths", def: [3, 5, 8, 12, 20], upgrade: [null,{"Deep Firefly":3,"Rupees":10},{"Frox Fang":3,"Dark Clump":5,"Rupees":50},{"Obsidian Frox Fang":3,"Zonaite":20,"Frox Fingernail":3,"Rupees":200},{"Blue-White Frox Fang":5,"Large Zonaite":10,"Frox Guts":3,"Rupees":500}] },
	{ id: 47, name: "Tunic of the Depths", maxlevel: 4, bodypart: "Torso", effect: "Gloom Resistance", set: "Depths", def: [3, 5, 8, 12, 20], upgrade: [null,{"Deep Firefly":3,"Rupees":10},{"Frox Fang":3,"Dark Clump":5,"Rupees":50},{"Obsidian Frox Fang":3,"Zonaite":20,"Frox Fingernail":3,"Rupees":200},{"Blue-White Frox Fang":5,"Large Zonaite":10,"Frox Guts":3,"Rupees":500}] },
	{ id: 48, name: "Gaiters of the Depths", maxlevel: 4, bodypart: "Legs", effect: "Gloom Resistance", set: "Depths", def: [3, 5, 8, 12, 20], upgrade: [null,{"Deep Firefly":3,"Rupees":10},{"Frox Fang":3,"Dark Clump":5,"Rupees":50},{"Obsidian Frox Fang":3,"Zonaite":20,"Frox Fingernail":3,"Rupees":200},{"Blue-White Frox Fang":5,"Large Zonaite":10,"Frox Guts":3,"Rupees":500}] },
	{ id: 49, name: "Miner's Mask", maxlevel: 4, bodypart: "Head", effect: "Glow", set: "Miner's", def: [3, 5, 8, 12, 20], upgrade: [null,{"Brightbloom Seed":10,"Rupees":10},{"Brightbloom Seed":20,"Brightcap":5,"Rupees":50},{"Giant Brightbloom Seed":15,"Glowing Cave Fish":5,"Deep Firefly":10,"Rupees":200},{"Giant Brightbloom Seed":20,"Diamond":3,"Large Zonaite":10,"Rupees":500}] },
	{ id: 50, name: "Miner's Top", maxlevel: 4, bodypart: "Torso", effect: "Glow", set: "Miner's", def: [3, 5, 8, 12, 20], upgrade: [null,{"Brightbloom Seed":10,"Rupees":10},{"Brightbloom Seed":20,"Brightcap":5,"Rupees":50},{"Giant Brightbloom Seed":15,"Glowing Cave Fish":5,"Deep Firefly":10,"Rupees":200},{"Giant Brightbloom Seed":20,"Diamond":3,"Large Zonaite":10,"Rupees":500}] },
	{ id: 51, name: "Miner's Trousers", maxlevel: 4, bodypart: "Legs", effect: "Glow", set: "Miner's", def: [3, 5, 8, 12, 20], upgrade: [null,{"Brightbloom Seed":10,"Rupees":10},{"Brightbloom Seed":20,"Brightcap":5,"Rupees":50},{"Giant Brightbloom Seed":15,"Glowing Cave Fish":5,"Deep Firefly":10,"Rupees":200},{"Giant Brightbloom Seed":20,"Diamond":3,"Large Zonaite":10,"Rupees":500}] },
	{ id: 52, name: "Mystic Headpiece", maxlevel: 0, bodypart: "Head", effect: "Rupee Padding", set: "Mystic", def: [3], upgrade: [] },
	{ id: 53, name: "Mystic Robe", maxlevel: 0, bodypart: "Torso", effect: "Rupee Padding", set: "Mystic", def: [3], upgrade: [] },
	{ id: 54, name: "Mystic Trousers", maxlevel: 0, bodypart: "Legs", effect: "Rupee Padding", set: "Mystic", def: [3], upgrade: [] },
	{ id: 55, name: "Ember Headdress", maxlevel: 4, bodypart: "Head", effect: "Hot Weather Attack", set: "Ember", def: [2, 4, 6, 9, 16], upgrade: [null,{"Fire Fruit":3,"Rupees":10},{"Fire-Breath Lizalfos Horn":5,"Summerwing Butterfly":5,"Rupees":50},{"Fire Like Stone":5,"Warm Darner":5,"Large Zonai Charge":5,"Rupees":200},{"Gleeok Flame Horn":5,"Sizzlefin Trout":10,"Large Zonai Charge":10,"Rupees":500}] },
	{ id: 56, name: "Ember Shirt", maxlevel: 4, bodypart: "Torso", effect: "Hot Weather Attack", set: "Ember", def: [2, 4, 6, 9, 16], upgrade: [null,{"Fire Fruit":3,"Rupees":10},{"Fire-Breath Lizalfos Horn":5,"Summerwing Butterfly":5,"Rupees":50},{"Fire Like Stone":5,"Warm Darner":5,"Large Zonai Charge":5,"Rupees":200},{"Gleeok Flame Horn":5,"Sizzlefin Trout":10,"Large Zonai Charge":10,"Rupees":500}] },
	{ id: 57, name: "Ember Trousers", maxlevel: 4, bodypart: "Legs", effect: "Hot Weather Attack", set: "Ember", def: [2, 4, 6, 9, 16], upgrade: [null,{"Fire Fruit":3,"Rupees":10},{"Fire-Breath Lizalfos Horn":5,"Summerwing Butterfly":5,"Rupees":50},{"Fire Like Stone":5,"Warm Darner":5,"Large Zonai Charge":5,"Rupees":200},{"Gleeok Flame Horn":5,"Sizzlefin Trout":10,"Large Zonai Charge":10,"Rupees":500}] },
	{ id: 58, name: "Charged Headdress", maxlevel: 4, bodypart: "Head", effect: "Stormy Weather Attack", set: "Charged", def: [3, 5, 8, 12, 20], upgrade: [null,{"Shock Fruit":3,"Rupees":10},{"Electric Lizalfos Horn":5,"Thunderwing Butterfly":3,"Rupees":50},{"Shock Like Stone":5,"Electric Darner":5,"Large Zonai Charge":3,"Rupees":200},{"Gleeok Thunder Horn":5,"Voltfin Trout":10,"Large Zonai Charge":5,"Rupees":500}] },
	{ id: 59, name: "Charged Shirt", maxlevel: 4, bodypart: "Torso", effect: "Stormy Weather Attack", set: "Charged", def: [3, 5, 8, 12, 20], upgrade: [null,{"Shock Fruit":3,"Rupees":10},{"Electric Lizalfos Horn":5,"Thunderwing Butterfly":3,"Rupees":50},{"Shock Like Stone":5,"Electric Darner":5,"Large Zonai Charge":3,"Rupees":200},{"Gleeok Thunder Horn":5,"Voltfin Trout":10,"Large Zonai Charge":5,"Rupees":500}] },
	{ id: 60, name: "Charged Trousers", maxlevel: 4, bodypart: "Legs", effect: "Stormy Weather Attack", set: "Charged", def: [3, 5, 8, 12, 20], upgrade: [null,{"Shock Fruit":3,"Rupees":10},{"Electric Lizalfos Horn":5,"Thunderwing Butterfly":3,"Rupees":50},{"Shock Like Stone":5,"Electric Darner":5,"Large Zonai Charge":3,"Rupees":200},{"Gleeok Thunder Horn":5,"Voltfin Trout":10,"Large Zonai Charge":5,"Rupees":500}] },
	{ id: 61, name: "Frostbite Headdress", maxlevel: 4, bodypart: "Head", effect: "Cold Weather Attack", set: "Frostbite", def: [2, 4, 6, 9, 16], upgrade: [null,{"Ice Fruit":3,"Rupees":10},{"Ice-Breath Lizalfos Horn":5,"Winterwing Butterfly":5,"Rupees":50},{"Ice Like Stone":5,"Cold Darner":5,"Large Zonai Charge":5,"Rupees":200},{"Gleeok Frost Horn":5,"Chillfin Trout":10,"Large Zonai Charge":10,"Rupees":500}] },
	{ id: 62, name: "Frostbite Shirt", maxlevel: 4, bodypart: "Torso", effect: "Cold Weather Attack", set: "Frostbite", def: [2, 4, 6, 9, 16], upgrade: [null,{"Ice Fruit":3,"Rupees":10},{"Ice-Breath Lizalfos Horn":5,"Winterwing Butterfly":5,"Rupees":50},{"Ice Like Stone":5,"Cold Darner":5,"Large Zonai Charge":5,"Rupees":200},{"Gleeok Frost Horn":5,"Chillfin Trout":10,"Large Zonai Charge":10,"Rupees":500}] },
	{ id: 63, name: "Frostbite Trousers", maxlevel: 4, bodypart: "Legs", effect: "Cold Weather Attack", set: "Frostbite", def: [2, 4, 6, 9, 16], upgrade: [null,{"Ice Fruit":3,"Rupees":10},{"Ice-Breath Lizalfos Horn":5,"Winterwing Butterfly":5,"Rupees":50},{"Ice Like Stone":5,"Cold Darner":5,"Large Zonai Charge":5,"Rupees":200},{"Gleeok Frost Horn":5,"Chillfin Trout":10,"Large Zonai Charge":10,"Rupees":500}] },
	{ id: 64, name: "Yiga Mask", maxlevel: 4, bodypart: "Head", effect: "Stealth Up", set: "Yiga", def: [1, 3, 5, 7, 12], upgrade: [null,{"Octorok Eyeball":2,"Rupees":10},{"Fire-Breath Lizalfos Tail":3,"Puffshroom":3,"Rupees":50},{"Ice-Breath Lizalfos Tail":5,"Keese Eyeball":5,"Rupees":200},{"Electric Lizalfos Tail":5,"Black Hinox Horn":3,"Mighty Bananas":10,"Rupees":500}] },
	{ id: 65, name: "Yiga Armor", maxlevel: 4, bodypart: "Torso", effect: "Stealth Up", set: "Yiga", def: [1, 3, 5, 7, 12], upgrade: [null,{"Octorok Eyeball":2,"Rupees":10},{"Fire-Breath Lizalfos Tail":3,"Puffshroom":3,"Rupees":50},{"Ice-Breath Lizalfos Tail":5,"Keese Eyeball":5,"Rupees":200},{"Electric Lizalfos Tail":5,"Black Hinox Horn":3,"Mighty Bananas":10,"Rupees":500}] },
	{ id: 66, name: "Yiga Tights", maxlevel: 4, bodypart: "Legs", effect: "Stealth Up", set: "Yiga", def: [1, 3, 5, 7, 12], upgrade: [null,{"Octorok Eyeball":2,"Rupees":10},{"Fire-Breath Lizalfos Tail":3,"Puffshroom":3,"Rupees":50},{"Ice-Breath Lizalfos Tail":5,"Keese Eyeball":5,"Rupees":200},{"Electric Lizalfos Tail":5,"Black Hinox Horn":3,"Mighty Bananas":10,"Rupees":500}] },
	{ id: 67, name: "Vah Medoh Divine Helm", maxlevel: 4, bodypart: "Head", effect: "Cold Resistance", set: false, def: [2, 4, 6, 9, 16], upgrade: [null,{"Sapphire":1,"Zonaite":5,"Rupees":10},{"Sapphire":4,"Zonaite":10,"Rupees":50},{"Sapphire":6,"Large Zonaite":5,"Dazzlefruit":5,"Rupees":200},{"Sapphire":10,"Large Zonaite":10,"Dazzlefruit":10,"Rupees":500}] },
	{ id: 68, name: "Vah Rudania Divine Helm", maxlevel: 4, bodypart: "Head", effect: "Flame Guard", set: false, def: [2, 4, 6, 9, 16], upgrade: [null,{"Ruby":1,"Zonaite":5,"Rupees":10},{"Ruby":4,"Zonaite":10,"Rupees":50},{"Ruby":6,"Large Zonaite":5,"Dazzlefruit":5,"Rupees":200},{"Ruby":10,"Large Zonaite":10,"Dazzlefruit":10,"Rupees":500}] },
	{ id: 69, name: "Vah Ruta Divine Helm", maxlevel: 4, bodypart: "Head", effect: "Swim Speed Up", set: false, def: [2, 4, 6, 9, 16], upgrade: [null,{"Opal":5,"Zonaite":5,"Rupees":10},{"Opal":10,"Zonaite":10,"Rupees":50},{"Opal":15,"Large Zonaite":5,"Dazzlefruit":5,"Rupees":200},{"Opal":25,"Large Zonaite":10,"Dazzlefruit":10,"Rupees":500}] },
	{ id: 70, name: "Vah Naboris Divine Helm", maxlevel: 4, bodypart: "Head", effect: "Shock Resistance", set: false, def: [2, 4, 6, 9, 16], upgrade: [null,{"Topaz":1,"Zonaite":5,"Rupees":10},{"Topaz":4,"Zonaite":10,"Rupees":50},{"Topaz":6,"Large Zonaite":5,"Dazzlefruit":5,"Rupees":200},{"Topaz":10,"Large Zonaite":10,"Dazzlefruit":10,"Rupees":500}] },
	{ id: 71, name: "Zonaite Helm", maxlevel: 4, bodypart: "Head", effect: "Energy Up", set: "Zonaite", def: [4, 7, 12, 18, 28], upgrade: [null,{"Soldier Construct Horn":5,"Rupees":10},{"Soldier Construct II Horn":5,"Captain Construct I Horn":5,"Zonaite":5,"Rupees":50},{"Soldier Construct III Horn":5,"Captain Construct II Horn":5,"Large Zonaite":5,"Rupees":200},{"Soldier Construct IV Horn":5,"Captain Construct III Horn":5,"Large Zonaite":10,"Rupees":500}] },
	{ id: 72, name: "Zonaite Waistguard", maxlevel: 4, bodypart: "Torso", effect: "Energy Up", set: "Zonaite", def: [4, 7, 12, 18, 28], upgrade: [null,{"Soldier Construct Horn":5,"Rupees":10},{"Soldier Construct II Horn":5,"Captain Construct I Horn":5,"Zonaite":5,"Rupees":50},{"Soldier Construct III Horn":5,"Captain Construct II Horn":5,"Large Zonaite":5,"Rupees":200},{"Soldier Construct IV Horn":5,"Captain Construct III Horn":5,"Large Zonaite":10,"Rupees":500}] },
	{ id: 73, name: "Zonaite Shin Guards", maxlevel: 4, bodypart: "Legs", effect: "Energy Up", set: "Zonaite", def: [4, 7, 12, 18, 28], upgrade: [null,{"Soldier Construct Horn":5,"Rupees":10},{"Soldier Construct II Horn":5,"Captain Construct I Horn":5,"Zonaite":5,"Rupees":50},{"Soldier Construct III Horn":5,"Captain Construct II Horn":5,"Large Zonaite":5,"Rupees":200},{"Soldier Construct IV Horn":5,"Captain Construct III Horn":5,"Large Zonaite":10,"Rupees":500}] },
	{ id: 74, name: "Diamond Circlet", maxlevel: 4, bodypart: "Head", effect: "Attack Up", set: false, def: [4, 7, 12, 18, 28], upgrade: [null,{"Diamond":2,"Flint":3,"Rupees":10},{"Diamond":3,"Flint":5,"Rupees":50},{"Diamond":5,"Star Fragment":1,"Rupees":200},{"Diamond":8,"Star Fragment":2,"Rupees":500}] },
	{ id: 75, name: "Ruby Circlet", maxlevel: 4, bodypart: "Head", effect: "Cold Resistance", set: false, def: [3, 5, 8, 12, 20], upgrade: [null,{"Ruby":2,"Flint":3,"Rupees":10},{"Ruby":4,"Flint":5,"Rupees":50},{"Ruby":6,"Star Fragment":1,"Rupees":200},{"Ruby":10,"Star Fragment":2,"Rupees":500}] },
	{ id: 76, name: "Sapphire Circlet", maxlevel: 4, bodypart: "Head", effect: "Heat Resistance", set: false, def: [3, 5, 8, 12, 20], upgrade: [null,{"Sapphire":2,"Flint":3,"Rupees":10},{"Sapphire":4,"Flint":5,"Rupees":50},{"Sapphire":6,"Star Fragment":1,"Rupees":200},{"Sapphire":10,"Star Fragment":2,"Rupees":500}] },
	{ id: 77, name: "Topaz Earrings", maxlevel: 4, bodypart: "Head", effect: "Shock Resistance", set: false, def: [3, 5, 8, 12, 18], upgrade: [null,{"Topaz":2,"Flint":3,"Rupees":10},{"Topaz":4,"Flint":5,"Rupees":50},{"Topaz":6,"Star Fragment":1,"Rupees":200},{"Topaz":10,"Star Fragment":2,"Rupees":500}] },
	{ id: 78, name: "Opal Earrings", maxlevel: 4, bodypart: "Head", effect: "Swim Speed Up", set: false, def: [3, 5, 8, 12, 20], upgrade: [null,{"Opal":6,"Flint":5,"Rupees":10},{"Opal":12,"Flint":10,"Rupees":50},{"Opal":18,"Flint":15,"Rupees":200},{"Opal":30,"Flint":25,"Rupees":500}] },
	{ id: 79, name: "Amber Earrings", maxlevel: 4, bodypart: "Head", effect: false, set: false, def: [4, 7, 12, 18, 28], upgrade: [null,{"Amber":10,"Flint":5,"Rupees":10},{"Amber":20,"Flint":10,"Rupees":50},{"Amber":35,"Flint":15,"Rupees":200},{"Amber":60,"Flint":25,"Rupees":500}] },
	{ id: 80, name: "Well-Worn Hair Band", maxlevel: 0, bodypart: "Head", effect: false, set: false, def: [0], upgrade: [] },
	{ id: 81, name: "Cece Hat", maxlevel: 0, bodypart: "Head", effect: false, set: false, def: [3], upgrade: [] },
	{ id: 82, name: "Lightning Helm", maxlevel: 0, bodypart: "Head", effect: "Lightning Proof", set: false, def: [3], upgrade: [] },
	{ id: 83, name: "Sand Boots", maxlevel: 4, bodypart: "Legs", effect: "Sand Speed Up", set: false, def: [3, 5, 8, 12, 20], upgrade: [null,{"Hightail Lizard":3,"Rupees":10},{"Gibdo Bone":20,"Swift Carrot":5,"Rupees":50},{"Gibdo Guts":5,"Rushroom":10,"Molduga Fin":5,"Rupees":200},{"Molduga Guts":5,"Swift Violet":10,"Hearty Lizard":5,"Rupees":500}] },
	{ id: 84, name: "Snow Boots", maxlevel: 4, bodypart: "Legs", effect: "Snow Speed Up", set: false, def: [3, 5, 8, 12, 20], upgrade: [null,{"Hightail Lizard":3,"Rupees":10},{"Octorok Tentacle":5,"Swift Carrot":5,"Rupees":50},{"Octo Balloon":5,"Rushroom":20,"Rupees":200},{"Naydra's Scale":2,"Swift Violet":20,"Rupees":500}] },
	{ id: 85, name: "Bokoblin Mask", maxlevel: 0, bodypart: "Head", effect: false, set: false, def: [3], upgrade: [] },
	{ id: 86, name: "Horriblin Mask", maxlevel: 0, bodypart: "Head", effect: false, set: false, def: [3], upgrade: [] },
	{ id: 87, name: "Moblin Mask", maxlevel: 0, bodypart: "Head", effect: false, set: false, def: [3], upgrade: [] },
	{ id: 88, name: "Lizalfos Mask", maxlevel: 0, bodypart: "Head", effect: false, set: false, def: [3], upgrade: [] },
	{ id: 89, name: "Lynel Mask", maxlevel: 0, bodypart: "Head", effect: false, set: false, def: [3], upgrade: [] },
	{ id: 90, name: "Tunic of Memories", maxlevel: 4, bodypart: "Torso", effect: false, set: false, def: [4, 7, 12, 18, 28], upgrade: [null,{"Silent Princess":3,"Light Dragon's Scale":1,"Rupees":10},{"Silent Princess":3,"Light Dragon's Talon":1,"Farosh's Horn":2,"Rupees":50},{"Silent Princess":5,"Shard of Light Dragon's Fang":1,"Naydra's Horn":2,"Rupees":200},{"Silent Princess":10,"Light Dragon's Horn":1,"Dinraal's Horn":2,"Rupees":500}] },
	{ id: 91, name: "Champion's Leathers", maxlevel: 4, bodypart: "Torso", effect: false, set: false, def: [5, 8, 14, 22, 32], upgrade: [null,{"Silent Princess":3,"Light Dragon's Scale":2,"Rupees":10},{"Silent Princess":3,"Light Dragon's Talon":2,"Sundelion":10,"Rupees":50},{"Silent Princess":5,"Shard of Light Dragon's Fang":2,"Sundelion":15,"Rupees":200},{"Silent Princess":10,"Light Dragon's Horn":2,"Sundelion":20,"Rupees":500}] },
	{ id: 92, name: "Island Lobster Shirt", maxlevel: 0, bodypart: "Torso", effect: "Heat Resistance", set: false, def: [1], upgrade: [] },
	{ id: 93, name: "Ravio's Hood", maxlevel: 0, bodypart: "Head", effect: false, set: false, def: [2], upgrade: [] },
	{ id: 94, name: "Zant's Helmet", maxlevel: 0, bodypart: "Head", effect: "Unfreezable", set: false, def: [3], upgrade: [] },
	{ id: 95, name: "Midna's Helmet", maxlevel: 0, bodypart: "Head", effect: "Gloom Resistance", set: false, def: [7], upgrade: [] },
	{ id: 96, name: "Majora's Mask", maxlevel: 0, bodypart: "Head", effect: false, set: false, def: [1], upgrade: [] },
	{ id: 97, name: "Korok Mask", maxlevel: 0, bodypart: "Head", effect: false, set: false, def: [1], upgrade: [] },
	{ id: 98, name: "Tingle's Hood", maxlevel: 0, bodypart: "Head", effect: false, set: "Tingle", def: [2], upgrade: [] },
	{ id: 99, name: "Tingle's Shirt", maxlevel: 0, bodypart: "Torso", effect: false, set: "Tingle", def: [2], upgrade: [] },
	{ id: 100, name: "Tingle's Tights", maxlevel: 0, bodypart: "Legs", effect: false, set: "Tingle", def: [2], upgrade: [] },
	{ id: 101, name: "Phantom Helmet", maxlevel: 0, bodypart: "Head", effect: "Attack Up", set: "Phantom", def: [8], upgrade: [] },
	{ id: 102, name: "Phantom Armor", maxlevel: 0, bodypart: "Torso", effect: "Attack Up", set: "Phantom", def: [8], upgrade: [] },
	{ id: 103, name: "Phantom Greaves", maxlevel: 0, bodypart: "Legs", effect: "Attack Up", set: "Phantom", def: [8], upgrade: [] },
	{ id: 104, name: "Evil Spirit Mask", maxlevel: 0, bodypart: "Head", effect: "Stealth Up", set: "Evil Spirit", def: [4], upgrade: [] },
	{ id: 105, name: "Evil Spirit Armor", maxlevel: 0, bodypart: "Torso", effect: "Stealth Up", set: "Evil Spirit", def: [4], upgrade: [] },
	{ id: 106, name: "Evil Spirit Greaves", maxlevel: 0, bodypart: "Legs", effect: "Stealth Up", set: "Evil Spirit", def: [4], upgrade: [] },
	{ id: 107, name: "Sheik's Mask", maxlevel: 4, bodypart: "Head", effect: "Stealth Up", set: false, def: [2, 4, 6, 9, 16], upgrade: [null,{"Silent Princess":1,"Star Fragment":1,"Rupees":10},{"Silent Princess":2,"Star Fragment":2,"Rupees":50},{"Silent Princess":4,"Star Fragment":3,"Rupees":200},{"Silent Princess":8,"Star Fragment":4,"Rupees":500}] },
	{ id: 108, name: "Dark Hood", maxlevel: 0, bodypart: "Head", effect: false, set: "Dark", def: [3], upgrade: [] },
	{ id: 109, name: "Dark Tunic", maxlevel: 0, bodypart: "Torso", effect: false, set: "Dark", def: [3], upgrade: [] },
	{ id: 110, name: "Dark Trousers", maxlevel: 0, bodypart: "Legs", effect: false, set: "Dark", def: [3], upgrade: [] },
	{ id: 111, name: "Fierce Deity Mask", maxlevel: 4, bodypart: "Head", effect: "Attack Up", set: "Fierce Deity", def: [3, 5, 8, 12, 20], upgrade: [null,{"Hinox Toenail":5,"Dinraal's Scale":1,"Rupees":10},{"Hinox Tooth":5,"Dinraal's Claw":1,"Rupees":50},{"Hinox Guts":2,"Shard of Dinraal's Fang":1,"Rupees":200},{"Lynel Guts":2,"Dinraal's Horn":1,"Rupees":500}] },
	{ id: 112, name: "Fierce Deity Armor", maxlevel: 4, bodypart: "Torso", effect: "Attack Up", set: "Fierce Deity", def: [3, 5, 8, 12, 20], upgrade: [null,{"Hinox Toenail":5,"Naydra's Scale":1,"Rupees":10},{"Hinox Tooth":5,"Naydra's Claw":1,"Rupees":50},{"Hinox Guts":2,"Shard of Naydra's Fang":1,"Rupees":200},{"Lynel Guts":2,"Naydra's Horn":1,"Rupees":500}] },
	{ id: 113, name: "Fierce Deity Boots", maxlevel: 4, bodypart: "Legs", effect: "Attack Up", set: "Fierce Deity", def: [3, 5, 8, 12, 20], upgrade: [null,{"Hinox Toenail":5,"Farosh's Scale":1,"Rupees":10},{"Hinox Tooth":5,"Farosh's Claw":1,"Rupees":50},{"Hinox Guts":2,"Shard of Farosh's Fang":1,"Rupees":200},{"Lynel Guts":2,"Farosh's Horn":1,"Rupees":500}] },
	{ id: 114, name: "Mask of Awakening", maxlevel: 4, bodypart: "Head", effect: false, set: "Awakening", def: [3, 5, 8, 12, 20], upgrade: [null,{"Luminous Stone":10,"Star Fragment":1,"Rupees":10},{"Luminous Stone":15,"Star Fragment":1,"Rupees":50},{"Luminous Stone":20,"Star Fragment":1,"Rupees":200},{"Luminous Stone":30,"Star Fragment":1,"Rupees":500}] },
	{ id: 115, name: "Tunic of Awakening", maxlevel: 4, bodypart: "Torso", effect: false, set: "Awakening", def: [3, 5, 8, 12, 20], upgrade: [null,{"Luminous Stone":10,"Star Fragment":1,"Rupees":10},{"Luminous Stone":15,"Star Fragment":1,"Rupees":50},{"Luminous Stone":20,"Star Fragment":1,"Rupees":200},{"Luminous Stone":30,"Star Fragment":1,"Rupees":500}] },
	{ id: 116, name: "Trousers of Awakening", maxlevel: 4, bodypart: "Legs", effect: false, set: "Awakening", def: [3, 5, 8, 12, 20], upgrade: [null,{"Luminous Stone":10,"Star Fragment":1,"Rupees":10},{"Luminous Stone":15,"Star Fragment":1,"Rupees":50},{"Luminous Stone":20,"Star Fragment":1,"Rupees":200},{"Luminous Stone":30,"Star Fragment":1,"Rupees":500}] },
	{ id: 117, name: "Cap of the Wild", maxlevel: 4, bodypart: "Head", effect: false, set: "Wild", def: [4, 7, 12, 18, 28], upgrade: [null,{"Acorn":10,"Farosh's Scale":2,"Rupees":10},{"Courser Bee Honey":5,"Farosh's Claw":2,"Rupees":50},{"Energetic Rhino Beetle":3,"Shard of Farosh's Fang":2,"Shard of Farosh's Spike":5,"Rupees":200},{"Star Fragment":3,"Farosh's Horn":2,"Shard of Farosh's Spike":10,"Rupees":500}] },
	{ id: 118, name: "Tunic of the Wild", maxlevel: 4, bodypart: "Torso", effect: false, set: "Wild", def: [4, 7, 12, 18, 28], upgrade: [null,{"Acorn":10,"Naydra's Scale":2,"Rupees":10},{"Courser Bee Honey":5,"Naydra's Claw":2,"Rupees":50},{"Energetic Rhino Beetle":3,"Shard of Naydra's Fang":2,"Shard of Naydra's Spike":5,"Rupees":200},{"Star Fragment":3,"Naydra's Horn":2,"Shard of Naydra's Spike":10,"Rupees":500}] },
	{ id: 119, name: "Trousers of the Wild", maxlevel: 4, bodypart: "Legs", effect: false, set: "Wild", def: [4, 7, 12, 18, 28], upgrade: [null,{"Acorn":10,"Dinraal's Scale":2,"Rupees":10},{"Courser Bee Honey":5,"Dinraal's Claw":2,"Rupees":50},{"Energetic Rhino Beetle":3,"Shard of Dinraal's Fang":2,"Shard of Dinraal's Spike":5,"Rupees":200},{"Star Fragment":3,"Dinraal's Horn":2,"Shard of Dinraal's Spike":10,"Rupees":500}] },
	{ id: 120, name: "Cap of the Hero", maxlevel: 4, bodypart: "Head", effect: false, set: "Hero", def: [3, 5, 8, 12, 20], upgrade: [null,{"Ruby":1,"Star Fragment":1,"Rupees":10},{"Ruby":4,"Star Fragment":1,"Rupees":50},{"Ruby":6,"Star Fragment":1,"Rupees":200},{"Ruby":10,"Star Fragment":1,"Rupees":500}] },
	{ id: 121, name: "Tunic of the Hero", maxlevel: 4, bodypart: "Torso", effect: false, set: "Hero", def: [3, 5, 8, 12, 20], upgrade: [null,{"Ruby":1,"Star Fragment":1,"Rupees":10},{"Ruby":4,"Star Fragment":1,"Rupees":50},{"Ruby":6,"Star Fragment":1,"Rupees":200},{"Ruby":10,"Star Fragment":1,"Rupees":500}] },
	{ id: 122, name: "Trousers of the Hero", maxlevel: 4, bodypart: "Legs", effect: false, set: "Hero", def: [3, 5, 8, 12, 20], upgrade: [null,{"Ruby":1,"Star Fragment":1,"Rupees":10},{"Ruby":4,"Star Fragment":1,"Rupees":50},{"Ruby":6,"Star Fragment":1,"Rupees":200},{"Ruby":10,"Star Fragment":1,"Rupees":500}] },
	{ id: 123, name: "Cap of Time", maxlevel: 4, bodypart: "Head", effect: false, set: "Time", def: [3, 5, 8, 12, 20], upgrade: [null,{"Amber":10,"Star Fragment":1,"Rupees":10},{"Amber":20,"Star Fragment":1,"Rupees":50},{"Amber":30,"Star Fragment":1,"Rupees":200},{"Amber":40,"Star Fragment":1,"Rupees":500}] },
	{ id: 124, name: "Tunic of Time", maxlevel: 4, bodypart: "Torso", effect: false, set: "Time", def: [3, 5, 8, 12, 20], upgrade: [null,{"Amber":10,"Star Fragment":1,"Rupees":10},{"Amber":20,"Star Fragment":1,"Rupees":50},{"Amber":30,"Star Fragment":1,"Rupees":200},{"Amber":40,"Star Fragment":1,"Rupees":500}] },
	{ id: 125, name: "Trousers of Time", maxlevel: 4, bodypart: "Legs", effect: false, set: "Time", def: [3, 5, 8, 12, 20], upgrade: [null,{"Amber":10,"Star Fragment":1,"Rupees":10},{"Amber":20,"Star Fragment":1,"Rupees":50},{"Amber":30,"Star Fragment":1,"Rupees":200},{"Amber":40,"Star Fragment":1,"Rupees":500}] },
	{ id: 126, name: "Cap of the Wind", maxlevel: 4, bodypart: "Head", effect: false, set: "Wind", def: [3, 5, 8, 12, 20], upgrade: [null,{"Opal":5,"Star Fragment":1,"Rupees":10},{"Opal":10,"Star Fragment":1,"Rupees":50},{"Opal":15,"Star Fragment":1,"Rupees":200},{"Opal":25,"Star Fragment":1,"Rupees":500}] },
	{ id: 127, name: "Tunic of the Wind", maxlevel: 4, bodypart: "Torso", effect: false, set: "Wind", def: [3, 5, 8, 12, 20], upgrade: [null,{"Opal":5,"Star Fragment":1,"Rupees":10},{"Opal":10,"Star Fragment":1,"Rupees":50},{"Opal":15,"Star Fragment":1,"Rupees":200},{"Opal":25,"Star Fragment":1,"Rupees":500}] },
	{ id: 128, name: "Trousers of the Wind", maxlevel: 4, bodypart: "Legs", effect: false, set: "Wind", def: [3, 5, 8, 12, 20], upgrade: [null,{"Opal":5,"Star Fragment":1,"Rupees":10},{"Opal":10,"Star Fragment":1,"Rupees":50},{"Opal":15,"Star Fragment":1,"Rupees":200},{"Opal":25,"Star Fragment":1,"Rupees":500}] },
	{ id: 129, name: "Cap of Twilight", maxlevel: 4, bodypart: "Head", effect: false, set: "Twilight", def: [3, 5, 8, 12, 20], upgrade: [null,{"Topaz":1,"Star Fragment":1,"Rupees":10},{"Topaz":4,"Star Fragment":1,"Rupees":50},{"Topaz":6,"Star Fragment":1,"Rupees":200},{"Topaz":10,"Star Fragment":1,"Rupees":500}] },
	{ id: 130, name: "Tunic of Twilight", maxlevel: 4, bodypart: "Torso", effect: false, set: "Twilight", def: [3, 5, 8, 12, 20], upgrade: [null,{"Topaz":1,"Star Fragment":1,"Rupees":10},{"Topaz":4,"Star Fragment":1,"Rupees":50},{"Topaz":6,"Star Fragment":1,"Rupees":200},{"Topaz":10,"Star Fragment":1,"Rupees":500}] },
	{ id: 131, name: "Trousers of Twilight", maxlevel: 4, bodypart: "Legs", effect: false, set: "Twilight", def: [3, 5, 8, 12, 20], upgrade: [null,{"Topaz":1,"Star Fragment":1,"Rupees":10},{"Topaz":4,"Star Fragment":1,"Rupees":50},{"Topaz":6,"Star Fragment":1,"Rupees":200},{"Topaz":10,"Star Fragment":1,"Rupees":500}] },
	{ id: 132, name: "Cap of the Sky", maxlevel: 4, bodypart: "Head", effect: false, set: "Sky", def: [3, 5, 8, 12, 20], upgrade: [null,{"Sapphire":1,"Star Fragment":1,"Rupees":10},{"Sapphire":4,"Star Fragment":1,"Rupees":50},{"Sapphire":6,"Star Fragment":1,"Rupees":200},{"Sapphire":10,"Star Fragment":1,"Rupees":500}] },
	{ id: 133, name: "Tunic of the Sky", maxlevel: 4, bodypart: "Torso", effect: false, set: "Sky", def: [3, 5, 8, 12, 20], upgrade: [null,{"Sapphire":1,"Star Fragment":1,"Rupees":10},{"Sapphire":4,"Star Fragment":1,"Rupees":50},{"Sapphire":6,"Star Fragment":1,"Rupees":200},{"Sapphire":10,"Star Fragment":1,"Rupees":500}] },
	{ id: 134, name: "Trousers of the Sky", maxlevel: 4, bodypart: "Legs", effect: false, set: "Sky", def: [3, 5, 8, 12, 20], upgrade: [null,{"Sapphire":1,"Star Fragment":1,"Rupees":10},{"Sapphire":4,"Star Fragment":1,"Rupees":50},{"Sapphire":6,"Star Fragment":1,"Rupees":200},{"Sapphire":10,"Star Fragment":1,"Rupees":500}] },
	{ id: 135, name: "Ancient Hero's Aspect", maxlevel: 4, bodypart: "Full Body", effect: false, set: "Ancient Hero", def: [12, 21, 36, 54, 84], upgrade: [null,{"Silver Bokoblin Horn":9,"Hinox Guts":9,"Zonaite":15,"Rupees":30},{"Silver Moblin Horn":9,"Frox Guts":9,"Large Zonaite":10,"Rupees":150},{"Silver Lizalfos Horn":9,"Molduga Guts":9,"Large Zonaite":15,"Rupees":600},{"Silver Lynel Saber Horn":9,"Silver Lynel Mace Horn":9,"Gleeok Guts":9,"Rupees":1500}] }
];

const materialInfo = {
	"Voltfruit": {"group": "Plant", "order_inventory": 1, "counts": [0, 0, 15, 0, 0]},
	"Mighty Bananas": {"group": "Plant", "order_inventory": 2, "counts": [0, 0, 0, 0, 30]},
	"Fire Fruit": {"group": "Plant", "order_inventory": 3, "counts": [0, 9, 0, 0, 0]},
	"Ice Fruit": {"group": "Plant", "order_inventory": 4, "counts": [0, 9, 0, 0, 0]},
	"Shock Fruit": {"group": "Plant", "order_inventory": 5, "counts": [0, 9, 0, 0, 0]},
	"Dazzlefruit": {"group": "Plant", "order_inventory": 6, "counts": [0, 0, 0, 20, 40]},
	"Puffshroom": {"group": "Plant", "order_inventory": 7, "counts": [0, 0, 9, 0, 0]},
	"Rushroom": {"group": "Plant", "order_inventory": 8, "counts": [0, 9, 0, 30, 0]},
	"Brightcap": {"group": "Plant", "order_inventory": 9, "counts": [0, 0, 15, 0, 0]},
	"Chillshroom": {"group": "Plant", "order_inventory": 10, "counts": [0, 0, 0, 15, 0]},
	"Sunshroom": {"group": "Plant", "order_inventory": 11, "counts": [0, 0, 0, 15, 0]},
	"Zapshroom": {"group": "Plant", "order_inventory": 12, "counts": [0, 0, 0, 15, 0]},
	"Silent Shroom": {"group": "Plant", "order_inventory": 13, "counts": [0, 0, 0, 24, 0]},
	"Razorshroom": {"group": "Plant", "order_inventory": 14, "counts": [0, 0, 15, 0, 0]},
	"Silent Princess": {"group": "Plant", "order_inventory": 15, "counts": [0, 7, 8, 14, 43]},
	"Swift Carrot": {"group": "Plant", "order_inventory": 16, "counts": [0, 0, 10, 0, 0]},
	"Cool Safflina": {"group": "Plant", "order_inventory": 17, "counts": [0, 0, 9, 0, 0]},
	"Warm Safflina": {"group": "Plant", "order_inventory": 18, "counts": [0, 0, 9, 0, 0]},
	"Mighty Thistle": {"group": "Plant", "order_inventory": 19, "counts": [0, 9, 0, 0, 0]},
	"Blue Nightshade": {"group": "Plant", "order_inventory": 20, "counts": [0, 9, 15, 0, 0]},
	"Electric Safflina": {"group": "Plant", "order_inventory": 21, "counts": [0, 0, 0, 24, 0]},
	"Swift Violet": {"group": "Plant", "order_inventory": 22, "counts": [0, 0, 0, 0, 90]},
	"Sundelion": {"group": "Plant", "order_inventory": 23, "counts": [0, 0, 10, 15, 50]},
	"Courser Bee Honey": {"group": "Plant", "order_inventory": 24, "counts": [0, 0, 15, 0, 0]},
	"Acorn": {"group": "Plant", "order_inventory": 25, "counts": [0, 30, 0, 0, 0]},
	"Dark Clump": {"group": "Monster", "order_inventory": 26, "counts": [0, 0, 15, 0, 0]},
	"Star Fragment": {"group": "Other", "order_inventory": 27, "counts": [0, 19, 20, 25, 39]},
	"Hearty Bass": {"group": "Creature", "order_inventory": 28, "counts": [0, 0, 0, 9, 0]},
	"Hyrule Bass": {"group": "Creature", "order_inventory": 29, "counts": [0, 0, 15, 0, 0]},
	"Chillfin Trout": {"group": "Creature", "order_inventory": 30, "counts": [0, 0, 0, 0, 30]},
	"Sizzlefin Trout": {"group": "Creature", "order_inventory": 31, "counts": [0, 0, 0, 0, 30]},
	"Voltfin Trout": {"group": "Creature", "order_inventory": 32, "counts": [0, 0, 0, 0, 30]},
	"Stealthfin Trout": {"group": "Creature", "order_inventory": 33, "counts": [0, 0, 0, 0, 30]},
	"Glowing Cave Fish": {"group": "Creature", "order_inventory": 34, "counts": [0, 0, 0, 15, 0]},
	"Sneaky River Snail": {"group": "Creature", "order_inventory": 35, "counts": [0, 0, 0, 15, 0]},
	"Razorclaw Crab": {"group": "Creature", "order_inventory": 36, "counts": [0, 0, 0, 9, 0]},
	"Winterwing Butterfly": {"group": "Creature", "order_inventory": 37, "counts": [0, 0, 15, 0, 0]},
	"Summerwing Butterfly": {"group": "Creature", "order_inventory": 38, "counts": [0, 0, 15, 0, 0]},
	"Thunderwing Butterfly": {"group": "Creature", "order_inventory": 39, "counts": [0, 0, 9, 0, 0]},
	"Smotherwing Butterfly": {"group": "Creature", "order_inventory": 40, "counts": [0, 0, 0, 9, 15]},
	"Cold Darner": {"group": "Creature", "order_inventory": 41, "counts": [0, 0, 0, 15, 0]},
	"Warm Darner": {"group": "Creature", "order_inventory": 42, "counts": [0, 0, 0, 15, 0]},
	"Electric Darner": {"group": "Creature", "order_inventory": 43, "counts": [0, 0, 0, 15, 0]},
	"Energetic Rhino Beetle": {"group": "Creature", "order_inventory": 44, "counts": [0, 0, 0, 9, 0]},
	"Bladed Rhino Beetle": {"group": "Creature", "order_inventory": 45, "counts": [0, 0, 0, 0, 9]},
	"Sunset Firefly": {"group": "Creature", "order_inventory": 46, "counts": [0, 0, 15, 0, 0]},
	"Deep Firefly": {"group": "Creature", "order_inventory": 47, "counts": [0, 9, 0, 30, 0]},
	"Hot-Footed Frog": {"group": "Creature", "order_inventory": 48, "counts": [0, 0, 0, 30, 0]},
	"Sticky Frog": {"group": "Creature", "order_inventory": 49, "counts": [0, 0, 0, 30, 0]},
	"Hearty Lizard": {"group": "Creature", "order_inventory": 50, "counts": [0, 0, 0, 0, 5]},
	"Hightail Lizard": {"group": "Creature", "order_inventory": 51, "counts": [0, 6, 15, 0, 0]},
	"Fireproof Lizard": {"group": "Creature", "order_inventory": 52, "counts": [0, 0, 15, 0, 0]},
	"Sticky Lizard": {"group": "Creature", "order_inventory": 53, "counts": [0, 9, 15, 0, 0]},
	"Diamond": {"group": "Other", "order_inventory": 54, "counts": [0, 2, 3, 5, 17]},
	"Ruby": {"group": "Other", "order_inventory": 55, "counts": [0, 6, 20, 30, 65]},
	"Sapphire": {"group": "Other", "order_inventory": 56, "counts": [0, 6, 20, 30, 65]},
	"Topaz": {"group": "Other", "order_inventory": 57, "counts": [0, 6, 20, 30, 65]},
	"Opal": {"group": "Other", "order_inventory": 58, "counts": [0, 26, 52, 78, 220]},
	"Amber": {"group": "Other", "order_inventory": 59, "counts": [0, 40, 80, 205, 390]},
	"Luminous Stone": {"group": "Other", "order_inventory": 60, "counts": [0, 60, 90, 120, 180]},
	"Flint": {"group": "Other", "order_inventory": 61, "counts": [0, 22, 40, 165, 140]},
	"Bokoblin Guts": {"group": "Monster", "order_inventory": 62, "counts": [0, 21, 0, 12, 20]},
	"Moblin Guts": {"group": "Monster", "order_inventory": 63, "counts": [0, 0, 15, 0, 0]},
	"Horriblin Guts": {"group": "Monster", "order_inventory": 64, "counts": [0, 0, 0, 9, 30]},
	"Gibdo Guts": {"group": "Monster", "order_inventory": 65, "counts": [0, 0, 0, 5, 0]},
	"Boss Bokoblin Guts": {"group": "Monster", "order_inventory": 66, "counts": [0, 0, 9, 0, 0]},
	"Lynel Guts": {"group": "Monster", "order_inventory": 67, "counts": [0, 0, 0, 0, 30]},
	"Gleeok Guts": {"group": "Monster", "order_inventory": 68, "counts": [0, 0, 0, 0, 18]},
	"Frox Guts": {"group": "Monster", "order_inventory": 69, "counts": [0, 0, 9, 0, 9]},
	"Molduga Guts": {"group": "Monster", "order_inventory": 70, "counts": [0, 0, 0, 9, 14]},
	"Hinox Guts": {"group": "Monster", "order_inventory": 71, "counts": [0, 9, 0, 24, 0]},
	"Red Chuchu Jelly": {"group": "Monster", "order_inventory": 72, "counts": [0, 9, 15, 0, 0]},
	"White Chuchu Jelly": {"group": "Monster", "order_inventory": 73, "counts": [0, 9, 15, 0, 0]},
	"Yellow Chuchu Jelly": {"group": "Monster", "order_inventory": 74, "counts": [0, 9, 24, 0, 0]},
	"Chuchu Jelly": {"group": "Monster", "order_inventory": 75, "counts": [0, 15, 0, 0, 0]},
	"Octo Balloon": {"group": "Monster", "order_inventory": 76, "counts": [0, 0, 0, 5, 0]},
	"Keese Eyeball": {"group": "Monster", "order_inventory": 77, "counts": [0, 0, 15, 15, 0]},
	"Octorok Eyeball": {"group": "Monster", "order_inventory": 78, "counts": [0, 6, 0, 0, 0]},
	"Aerocuda Eyeball": {"group": "Monster", "order_inventory": 79, "counts": [0, 0, 18, 24, 0]},
	"Keese Wing": {"group": "Monster", "order_inventory": 80, "counts": [0, 18, 15, 0, 0]},
	"Fire Keese Wing": {"group": "Monster", "order_inventory": 81, "counts": [0, 0, 0, 15, 30]},
	"Ice Keese Wing": {"group": "Monster", "order_inventory": 82, "counts": [0, 0, 0, 39, 0]},
	"Electric Keese Wing": {"group": "Monster", "order_inventory": 83, "counts": [0, 0, 15, 0, 0]},
	"Aerocuda Wing": {"group": "Monster", "order_inventory": 84, "counts": [0, 0, 0, 18, 30]},
	"Gibdo Wing": {"group": "Monster", "order_inventory": 85, "counts": [0, 0, 0, 0, 24]},
	"Gleeok Wing": {"group": "Monster", "order_inventory": 86, "counts": [0, 0, 0, 0, 36]},
	"Molduga Fin": {"group": "Monster", "order_inventory": 87, "counts": [0, 0, 0, 5, 0]},
	"Bokoblin Horn": {"group": "Monster", "order_inventory": 88, "counts": [0, 20, 0, 0, 0]},
	"Blue Bokoblin Horn": {"group": "Monster", "order_inventory": 89, "counts": [0, 0, 20, 0, 0]},
	"Black Bokoblin Horn": {"group": "Monster", "order_inventory": 90, "counts": [0, 0, 0, 20, 0]},
	"Silver Bokoblin Horn": {"group": "Monster", "order_inventory": 91, "counts": [0, 9, 0, 0, 20]},
	"Boss Bokoblin Horn": {"group": "Monster", "order_inventory": 92, "counts": [0, 9, 0, 0, 0]},
	"Blue Boss Bokoblin Horn": {"group": "Monster", "order_inventory": 93, "counts": [0, 0, 9, 0, 0]},
	"Black Boss Bokoblin Horn": {"group": "Monster", "order_inventory": 94, "counts": [0, 0, 0, 9, 0]},
	"Silver Boss Bokoblin Horn": {"group": "Monster", "order_inventory": 95, "counts": [0, 0, 0, 0, 9]},
	"Lizalfos Horn": {"group": "Monster", "order_inventory": 96, "counts": [0, 9, 0, 0, 0]},
	"Blue Lizalfos Horn": {"group": "Monster", "order_inventory": 97, "counts": [0, 0, 0, 15, 0]},
	"Black Lizalfos Horn": {"group": "Monster", "order_inventory": 98, "counts": [0, 0, 0, 0, 15]},
	"Silver Lizalfos Horn": {"group": "Monster", "order_inventory": 99, "counts": [0, 0, 0, 9, 0]},
	"Fire-Breath Lizalfos Horn": {"group": "Monster", "order_inventory": 100, "counts": [0, 0, 15, 0, 15]},
	"Ice-Breath Lizalfos Horn": {"group": "Monster", "order_inventory": 101, "counts": [0, 0, 15, 0, 15]},
	"Electric Lizalfos Horn": {"group": "Monster", "order_inventory": 102, "counts": [0, 3, 15, 0, 15]},
	"Lynel Saber Horn": {"group": "Monster", "order_inventory": 103, "counts": [0, 0, 6, 0, 0]},
	"Blue-Maned Lynel Saber Horn": {"group": "Monster", "order_inventory": 104, "counts": [0, 0, 0, 9, 0]},
	"White-Maned Lynel Saber Horn": {"group": "Monster", "order_inventory": 105, "counts": [0, 0, 0, 0, 9]},
	"Silver Lynel Saber Horn": {"group": "Monster", "order_inventory": 106, "counts": [0, 0, 0, 0, 9]},
	"Soldier Construct Horn": {"group": "Monster", "order_inventory": 107, "counts": [0, 15, 0, 0, 0]},
	"Soldier Construct II Horn": {"group": "Monster", "order_inventory": 108, "counts": [0, 0, 15, 0, 0]},
	"Soldier Construct III Horn": {"group": "Monster", "order_inventory": 109, "counts": [0, 0, 0, 15, 0]},
	"Soldier Construct IV Horn": {"group": "Monster", "order_inventory": 110, "counts": [0, 0, 0, 0, 15]},
	"Captain Construct I Horn": {"group": "Monster", "order_inventory": 111, "counts": [0, 0, 15, 0, 0]},
	"Captain Construct II Horn": {"group": "Monster", "order_inventory": 112, "counts": [0, 0, 0, 15, 0]},
	"Captain Construct III Horn": {"group": "Monster", "order_inventory": 113, "counts": [0, 0, 0, 0, 15]},
	"Hinox Toenail": {"group": "Monster", "order_inventory": 114, "counts": [0, 15, 0, 0, 0]},
	"Gleeok Flame Horn": {"group": "Monster", "order_inventory": 115, "counts": [0, 0, 0, 0, 15]},
	"Gleeok Frost Horn": {"group": "Monster", "order_inventory": 116, "counts": [0, 0, 0, 0, 15]},
	"Gleeok Thunder Horn": {"group": "Monster", "order_inventory": 117, "counts": [0, 0, 0, 0, 15]},
	"Dinraal's Horn": {"group": "Dragon", "order_inventory": 118, "counts": [0, 0, 0, 0, 5]},
	"Naydra's Horn": {"group": "Dragon", "order_inventory": 119, "counts": [0, 0, 0, 2, 3]},
	"Farosh's Horn": {"group": "Dragon", "order_inventory": 120, "counts": [0, 0, 2, 0, 3]},
	"Light Dragon's Horn": {"group": "Dragon", "order_inventory": 121, "counts": [0, 0, 0, 0, 3]},
	"Fire Like Stone": {"group": "Monster", "order_inventory": 122, "counts": [0, 0, 0, 15, 0]},
	"Ice Like Stone": {"group": "Monster", "order_inventory": 123, "counts": [0, 0, 0, 15, 0]},
	"Shock Like Stone": {"group": "Monster", "order_inventory": 124, "counts": [0, 0, 0, 15, 0]},
	"Moblin Horn": {"group": "Monster", "order_inventory": 125, "counts": [0, 9, 0, 0, 0]},
	"Blue Moblin Horn": {"group": "Monster", "order_inventory": 126, "counts": [0, 0, 0, 15, 0]},
	"Black Moblin Horn": {"group": "Monster", "order_inventory": 127, "counts": [0, 0, 0, 0, 15]},
	"Silver Moblin Horn": {"group": "Monster", "order_inventory": 128, "counts": [0, 0, 9, 0, 0]},
	"Horriblin Horn": {"group": "Monster", "order_inventory": 129, "counts": [0, 0, 15, 0, 0]},
	"Blue Horriblin Horn": {"group": "Monster", "order_inventory": 130, "counts": [0, 0, 0, 15, 0]},
	"Black Horriblin Horn": {"group": "Monster", "order_inventory": 131, "counts": [0, 0, 0, 0, 15]},
	"Lynel Hoof": {"group": "Monster", "order_inventory": 132, "counts": [0, 0, 0, 0, 15]},
	"Lynel Mace Horn": {"group": "Monster", "order_inventory": 133, "counts": [0, 0, 6, 0, 0]},
	"Blue-Maned Lynel Mace Horn": {"group": "Monster", "order_inventory": 134, "counts": [0, 0, 0, 9, 0]},
	"White-Maned Lynel Mace Horn": {"group": "Monster", "order_inventory": 135, "counts": [0, 0, 0, 0, 9]},
	"Silver Lynel Mace Horn": {"group": "Monster", "order_inventory": 136, "counts": [0, 0, 0, 0, 9]},
	"Black Hinox Horn": {"group": "Monster", "order_inventory": 137, "counts": [0, 0, 0, 0, 9]},
	"Molduga Jaw": {"group": "Monster", "order_inventory": 138, "counts": [0, 0, 0, 0, 9]},
	"Frox Fang": {"group": "Monster", "order_inventory": 139, "counts": [0, 0, 9, 0, 0]},
	"Obsidian Frox Fang": {"group": "Monster", "order_inventory": 140, "counts": [0, 0, 0, 9, 0]},
	"Blue-White Frox Fang": {"group": "Monster", "order_inventory": 141, "counts": [0, 0, 0, 0, 15]},
	"Shard of Dinraal's Spike": {"group": "Dragon", "order_inventory": 142, "counts": [0, 0, 0, 5, 10]},
	"Shard of Naydra's Spike": {"group": "Dragon", "order_inventory": 143, "counts": [0, 0, 0, 5, 10]},
	"Shard of Farosh's Spike": {"group": "Dragon", "order_inventory": 144, "counts": [0, 0, 0, 5, 10]},
	"Lizalfos Tail": {"group": "Monster", "order_inventory": 145, "counts": [0, 0, 0, 18, 0]},
	"Blue Lizalfos Tail": {"group": "Monster", "order_inventory": 146, "counts": [0, 0, 0, 0, 15]},
	"Fire-Breath Lizalfos Tail": {"group": "Monster", "order_inventory": 147, "counts": [0, 0, 9, 9, 30]},
	"Ice-Breath Lizalfos Tail": {"group": "Monster", "order_inventory": 148, "counts": [0, 0, 0, 24, 30]},
	"Electric Lizalfos Tail": {"group": "Monster", "order_inventory": 149, "counts": [0, 0, 0, 15, 39]},
	"Gibdo Bone": {"group": "Monster", "order_inventory": 150, "counts": [0, 0, 20, 30, 0]},
	"Octorok Tentacle": {"group": "Monster", "order_inventory": 151, "counts": [0, 0, 5, 0, 0]},
	"Bokoblin Fang": {"group": "Monster", "order_inventory": 152, "counts": [0, 0, 12, 0, 0]},
	"Moblin Fang": {"group": "Monster", "order_inventory": 153, "counts": [0, 0, 15, 0, 0]},
	"Hinox Tooth": {"group": "Monster", "order_inventory": 154, "counts": [0, 0, 15, 0, 0]},
	"Lizalfos Talon": {"group": "Monster", "order_inventory": 155, "counts": [0, 0, 15, 0, 0]},
	"Frox Fingernail": {"group": "Monster", "order_inventory": 156, "counts": [0, 0, 0, 9, 0]},
	"Dinraal's Scale": {"group": "Dragon", "order_inventory": 157, "counts": [0, 3, 0, 0, 0]},
	"Naydra's Scale": {"group": "Dragon", "order_inventory": 158, "counts": [0, 3, 0, 0, 2]},
	"Farosh's Scale": {"group": "Dragon", "order_inventory": 159, "counts": [0, 3, 0, 0, 0]},
	"Light Dragon's Scale": {"group": "Dragon", "order_inventory": 160, "counts": [0, 3, 0, 0, 0]},
	"Dinraal's Claw": {"group": "Dragon", "order_inventory": 161, "counts": [0, 0, 3, 0, 0]},
	"Naydra's Claw": {"group": "Dragon", "order_inventory": 162, "counts": [0, 0, 3, 0, 0]},
	"Farosh's Claw": {"group": "Dragon", "order_inventory": 163, "counts": [0, 0, 3, 0, 0]},
	"Light Dragon's Talon": {"group": "Dragon", "order_inventory": 164, "counts": [0, 0, 3, 0, 0]},
	"Shard of Dinraal's Fang": {"group": "Dragon", "order_inventory": 165, "counts": [0, 0, 0, 3, 0]},
	"Shard of Naydra's Fang": {"group": "Dragon", "order_inventory": 166, "counts": [0, 0, 0, 3, 0]},
	"Shard of Farosh's Fang": {"group": "Dragon", "order_inventory": 167, "counts": [0, 0, 0, 3, 0]},
	"Shard of Light Dragon's Fang": {"group": "Dragon", "order_inventory": 168, "counts": [0, 0, 0, 3, 0]},
	"Brightbloom Seed": {"group": "Plant", "order_inventory": 169, "counts": [0, 30, 60, 0, 0]},
	"Giant Brightbloom Seed": {"group": "Plant", "order_inventory": 170, "counts": [0, 0, 0, 45, 60]},
	"Zonaite": {"group": "Other", "order_inventory": 171, "counts": [0, 35, 55, 60, 0]},
	"Large Zonaite": {"group": "Other", "order_inventory": 172, "counts": [0, 0, 10, 50, 130]},
	"Large Zonai Charge": {"group": "Other", "order_inventory": 173, "counts": [0, 0, 0, 39, 75]},
	"Rupees": {"group": "Other", "order_inventory": 174, "counts": [0, 1060, 5300, 21200, 53000]}
};

/*const setInfo = {
	"Hylian": {"effect": false, "setbonus": false},
	"Soldier's": {"effect": false, "setbonus": false},
	"Snowquill": {"effect": "Cold Resistance", "setbonus": "Unfreezable (Set)"},
	"Flamebreaker": {"effect": "Flame Guard", "setbonus": "Fireproof"},
	"Zora": {"effect": "Swim Speed Up", "setbonus": "Swim Dash Stamina Up"},
	"Desert Voe": {"effect": "Heat Resistance", "setbonus": "Shock Damage Resist"},
	"Rubber": {"effect": "Shock Resistance", "setbonus": "Lightning Proof (Set)"},
	"Stealth": {"effect": "Stealth Up", "setbonus": "Night Speed Up"},
	"Climbing Gear": {"effect": "Climb Speed Up", "setbonus": "Climbing Jump Stamina Up"},
	"Barbarian": {"effect": "Attack Up", "setbonus": "Charge Atk. Stamina Up"},
	"Radiant": {"effect": false, "setbonus": "Disguise; Bone Weap. Prof."},
	"Royal Guard": {"effect": false, "setbonus": "Charge Atk. Stamina Up"},
	"Froggy": {"effect": "Slip Resistance", "setbonus": "Slip Proof"},
	"Glide": {"effect": "Skydive Mobility Up", "setbonus": "Impact Proof"},
	"Depths": {"effect": "Gloom Resistance", "setbonus": "Gloom Attack Resist"},
	"Miner's": {"effect": "Glow", "setbonus": "Shining Steps"},
	"Mystic": {"effect": "Rupee Padding", "setbonus": false},
	"Ember": {"effect": "Hot Weather Attack", "setbonus": "Hot Weather Charge"},
	"Charged": {"effect": "Stormy Weather Attack", "setbonus": "Stormy Weather Charge"},
	"Frostbite": {"effect": "Cold Weather Attack", "setbonus": "Cold Weather Charge"},
	"Yiga": {"effect": "Stealth Up", "setbonus": "Night Speed Up"},
	"Zonaite": {"effect": "Energy Up", "setbonus": "Energy Recharge Up"},
	"Tingle": {"effect": false, "setbonus": "Night Speed Up (Set)"},
	"Phantom": {"effect": "Attack Up", "setbonus": false},
	"Evil Spirit": {"effect": "Stealth Up", "setbonus": "Disguise; Bone Weap. Prof."},
	"Dark": {"effect": false, "setbonus": "Night Speed Up (Set)"},
	"Fierce Deity": {"effect": "Attack Up", "setbonus": "Charge Atk. Stamina Up"},
	"Awakening": {"effect": false, "setbonus": "Attack Up (Set)"},
	"Wild": {"effect": false, "setbonus": "Attack Up (Set)"},
	"Hero": {"effect": false, "setbonus": "Attack Up (Set)"},
	"Time": {"effect": false, "setbonus": "Attack Up (Set)"},
	"Wind": {"effect": false, "setbonus": "Attack Up (Set)"},
	"Twilight": {"effect": false, "setbonus": "Attack Up (Set)"},
	"Sky": {"effect": false, "setbonus": "Attack Up (Set)"},
	"Ancient Hero": {"effect": false, "setbonus": "Master Sword Beam Up"}
};*/